### PR TITLE
EZEE-2936: Added package for content comparison bundle

### PR DESCRIPTION
**Pull request by ViniTou**
Add package for EE metarepo.

# todo:

~package is still not in satis, do not merge now, even if build is green as currently travis does nothing for this metarepo.~

### CODE REVIEW

**Comment by mnocon** [comment]
@alongosz good point and I agree with you, that would be useful. I thought about it a bit and it would require an investigation how to make that secure.

Let's consider a scenario like this:
- we set up this repo with our Satis credentials on Travis, so it can install private packages
- env variables are available for PRs from `ezsystems`, not for forks - meaning that we could do a simple if statement and stop the build early if it's started from the fork.

There are some things that would work out of the box with this approach:
- env variables are not available from forks, so it's not possible for someone outside our company to modify the .travis.yml file and dump them into log, we're covered here

But there are other ways this could harm us - for example could someone create a PR from a fork, modify the .travis.yml to zip the contents of Composer cache and upload it somewhere, getting access to the private packages? (I don't know, I haven't tried it, but seems plausible - no env vars are needed for that, we also know it's possible to upload files from Travis to remote places).

So we would need to disable Composer cache as well, but right now I can't say that's all that's needed, hence the investigation 😉

**Comment by alongosz** [comment]
> But there are other ways this could harm us - for example could someone create a PR from a fork, modify the .travis.yml to zip the contents of Composer cache and upload it somewhere, getting access to the private packages?

Hmm, doesn't this mean that right now it is possible anyway?

**Comment by mnocon** [comment]
Travis setup for EE is in place only for private repositories (unavailable to the people outside our org), this one is a public one.

**Comment by alongosz** [comment]
> Travis setup for EE is in place only for private repositories (unavailable to people outside our org), this one is a public one.

I meant rather that someone can still modify the contents of this `.travis.yml` anyway. Is it not the case?

**Comment by ViniTou** [comment]
https://github.com/ezsystems/ezplatform-ee/pull/122

**Pull request closed without merging**
