### PR TITLE
Update cache_pool comment in ezplatform.yaml

### PR DESCRIPTION
**Pull request by barw4**
As the title states.

### CODE REVIEW

**Comment by lserwatka** [comment]
@mnocon could you merge it up and horizontally?

**Comment by mnocon** [comment]
@lserwatka sure, but this is ezplatform-ee - should we revert this one, merge https://github.com/ezsystems/ezplatform/pull/551 and then merge it here horizontally?

**Comment by lserwatka** [comment]
@mnocon yes, good catch! Will you take over?

**Comment by lserwatka** [comment]
@mnocon reverted

**Comment by mnocon** [comment]
Ok, I will do the merges now

**Pull request merged**
