### PR TITLE
EZEE-1444: Store StudioUI 3rd-party dependencies in a separate bundle

### PR DESCRIPTION
**Pull request by sunpietro**
https://jira.ez.no/browse/EZEE-1444

### CODE REVIEW

**Comment by lserwatka** [comment]
No, we should start with version 1.0.0, so ^1.0@dev and add branch alias to external repo for 1.0.x-dev

**Comment by lserwatka** [comment]
I would recommend to add this entry somewhere at the bottom, to avoid conflicts on upgrades on composer.json

**Comment by micszo** [comment]
I think https://github.com/ezsystems/ezplatform-ee-assets/pull/2 needs to be merged before this can be tested. :) (Now there is unresolved requirements issue.)

**Comment by lserwatka** [comment]
@sunpietro can you please move `ezsystems/ezplatform-ee-assets`, down to the bottom of the packages list, instead of adding it somewhere in the middle? Then we can close this PR.

**Comment by sunpietro** [comment]
@lserwatka done. Please, use the **Squash & merge** function to merge this PR :)

**Pull request merged**
