### PR TITLE
IBX-153: Workflow queries optimization

### PR DESCRIPTION
**Pull request by adamwojs**
> JIRA: https://issues.ibexa.co/browse/IBX-153

### Description

See https://github.com/ezsystems/ezplatform-workflow/pull/181

### CODE REVIEW

**Review by tomaszszopinski — CHANGES_REQUESTED** [review]
Hello, it seems that after adding indexes _idx_workflow_co_id_ver_ and _idx_wokrflow_name_  the following query Time spiked (in case of 2000 content items for about 200ms).

APP_ENV=behat
DATABASE_PLATFORM=mysql
DATABASE_DRIVER=pdo_mysql
DATABASE_VERSION=mariadb-10.3.0
DATABASE_CHARSET=utf8mb4
DATABASE_COLLATION=utf8mb4_unicode_520_ci


`SELECT w.id, w.content_id, w.version_no, w.workflow_name, w.initial_owner_id, w.start_date FROM ezeditorialworkflow_workflows w WHERE (NOT (w.id IN (SELECT wf.id FROM ezeditorialworkflow_markings m LEFT JOIN ezeditorialworkflow_workflows wf ON m.workflow_id = wf.id WHERE ((wf.workflow_name = :dcValue1) AND (m.name IN (:dcValue2))) OR ((wf.workflow_name = :dcValue3) AND (m.name IN (:dcValue4))) OR ((wf.workflow_name = :dcValue5) AND (m.name IN (:dcValue6))) OR ((wf.workflow_name = :dcValue7) AND (m.name IN (:dcValue8)))))) AND (NOT (w.id IN (SELECT wf.id FROM ezeditorialworkflow_markings m LEFT JOIN ezeditorialworkflow_workflows wf ON m.workflow_id = wf.id WHERE ((wf.workflow_name = 'quick_review') AND (m.name IN ('draft'))) OR ((wf.workflow_name = 'workflow1') AND (m.name IN ('draft'))) OR ((wf.workflow_name = 'workflow2') AND (m.name IN ('draft'))) OR ((wf.workflow_name = 'workflow3') AND (m.name IN ('draft'))) OR ((wf.workflow_name = 'workflow4') AND (m.name IN ('draft')))))) AND (NOT (w.id IN (SELECT wf.id FROM ezeditorialworkflow_workflows wf LEFT JOIN ezcontentobject c ON wf.content_id = c.id WHERE c.status = 2)))
Parameters:
[▼
  "dcValue1" => "workflow1"
  "dcValue2" => [▼
    "done"
  ]
  "dcValue3" => "workflow2"
  "dcValue4" => [▼
    "done"
  ]
  "dcValue5" => "workflow3"
  "dcValue6" => [▼
    "done"
  ]
  "dcValue7" => "workflow4"
  "dcValue8" => [▼
    "done"
  ]
]`

And the explanation:

> 

id | select_type | table | type | possible_keys | key | key_len | ref | rows | Extra
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | PRIMARY | w | ALL |   |   |   |   | 3802 | Using where
4 | MATERIALIZED | c | ref | PRIMARY, ezcontentobject_classid, ezcontentobject_lmask, ezcontentobject_pub, ezcontentobject_section, ezcontentobject_currentversion, ezcontentobject_owner, ezcontentobject_status | ezcontentobject_status | 5 | const | 1 | Using index
4 | MATERIALIZED | wf | ref | PRIMARY, idx_workflow_id, idx_workflow_co_id_ver | idx_workflow_co_id_ver | 4 | ezplat3ee.c.id | 1 | Using index
3 | MATERIALIZED | m | ALL | fk_workflow_id_markings |   |   |   | 3922 | Using where
3 | MATERIALIZED | wf | eq_ref | PRIMARY, idx_workflow_id, initial_owner_id, idx_workflow_co_id_ver, idx_workflow_name | PRIMARY | 4 | ezplat3ee.m.workflow_id | 1 | Using where
2 | MATERIALIZED | m | ALL | fk_workflow_id_markings |   |   |   | 3922 | Using where
2 | MATERIALIZED | wf | range\|filter | PRIMARY, idx_workflow_id, initial_owner_id, idx_workflow_co_id_ver, idx_workflow_name | idx_workflow_name\|idx_workflow_name | 1022\|1022 |   | 2022 (53%) | Using where; Using index; Using join buffer (flat, BNL join); Using rowid filter

**Comment by tomaszszopinski** [comment]
In case we have ~3500 item query looks like this: 
Zrzut ekranu 2021-04-16 o 12 38 05

**Comment by Steveb-p** [comment]
@tomaszszopinski can you provide the `explain` of this query before the index is introduced?

From what I understand, the issue here is that the MySQL uses `eq_ref` matching instead of `ref` matching. This is due to the fact that index is not unique, so database makes some assumptions about how the index should be used for comparison.
See:
https://stackoverflow.com/a/4528433/2424641
https://dev.mysql.com/doc/refman/8.0/en/explain-output.html#jointype_eq_ref

**Comment by tomaszszopinski** [comment]
Sure, explain for previous post is as. follows: 

id | select_type | table | type | possible_keys | key | key_len | ref | rows | Extra
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | PRIMARY | w | ALL |   |   |   |   | 10916 | Using where
4 | MATERIALIZED | c | ref | PRIMARY, ezcontentobject_classid, ezcontentobject_lmask, ezcontentobject_pub, ezcontentobject_section, ezcontentobject_currentversion, ezcontentobject_owner, ezcontentobject_status | ezcontentobject_status | 5 | const | 1 | Using index
4 | MATERIALIZED | wf | ref | PRIMARY, idx_workflow_id, idx_workflow_co_id_ver | idx_workflow_co_id_ver | 4 | ezplat3ee.c.id | 1 | Using index
3 | MATERIALIZED | m | ALL | fk_workflow_id_markings |   |   |   | 10418 | Using where
3 | MATERIALIZED | wf | eq_ref | PRIMARY, idx_workflow_id, initial_owner_id, idx_workflow_co_id_ver, idx_workflow_name | PRIMARY | 4 | ezplat3ee.m.workflow_id | 1 | Using where
2 | MATERIALIZED | m | ALL | fk_workflow_id_markings |   |   |   | 10418 | Using where
2 | MATERIALIZED | wf | range\|filter | PRIMARY, idx_workflow_id, initial_owner_id, idx_workflow_co_id_ver, idx_workflow_name | idx_workflow_name\|idx_workflow_name | 1022\|1022 |   | 5974 (55%) | Using where; Using index; Using join buffer (flat, BNL join); Using rowid filter

**Comment by Steveb-p** [comment]
@tomaszszopinski are you sure the second `explain` is for the version without indexes? They still do appear in it's output.

**Comment by tomaszszopinski** [comment]
@Steveb-p Sorry, here's a query without indexes (same db as on friday): 
Zrzut ekranu 2021-04-20 o 11 18 33


id | select_type | table | type | possible_keys | key | key_len | ref | rows | Extra
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | PRIMARY | w | ALL |   |   |   |   | 10745 | Using where
4 | MATERIALIZED | c | ref | PRIMARY, ezcontentobject_classid, ezcontentobject_lmask, ezcontentobject_pub, ezcontentobject_section, ezcontentobject_currentversion, ezcontentobject_owner, ezcontentobject_status | ezcontentobject_status | 5 | const | 1 | Using index
4 | MATERIALIZED | wf | ALL | PRIMARY, idx_workflow_id |   |   |   | 10745 | Using where; Using join buffer (flat, BNL join)
3 | MATERIALIZED | m | ALL | fk_workflow_id_markings |   |   |   | 10256 | Using where
3 | MATERIALIZED | wf | eq_ref | PRIMARY, idx_workflow_id, initial_owner_id | PRIMARY | 4 | ezplat3ee.m.workflow_id | 1 | Using where
2 | MATERIALIZED | m | ALL | fk_workflow_id_markings |   |   |   | 10256 | Using where
2 | MATERIALIZED | wf | eq_ref | PRIMARY, idx_workflow_id, initial_owner_id | PRIMARY | 4 | ezplat3ee.m.workflow_id | 1 | Using where

**Pull request closed without merging**
