### PR TITLE
EZP-29455: Enable eZ Behat extension. Disable Travis on metarepo

### PR DESCRIPTION
**Pull request by mnocon**
JIRA: https://jira.ez.no/browse/EZP-29455

Things done:
1) Enabling eZ Behat extension for this metarepo (required by tests in repository-forms, added in https://github.com/ezsystems/StudioUIBundle/pull/906).
2) Disabling Travis on this metarepo (to be more specific: making it always green, with a message). We cannot install the product without specifying secret tokens, which cannot be provided (it's a public repo). Currently all builds here are failing on composer install step.
3) Adjusting composer.json values - stable branch should allow installing dev packages, similar as in 1.7 branch of ezplatform: https://github.com/ezsystems/ezplatform/blob/1.7/composer.json#L30

### CODE REVIEW

**Comment by mnocon** [comment]
@andrerom could you have a look if the composer changes are correct?

**Comment by andrerom** [comment]
@mnocon To know if the composer changes are correct, check against ezplatform:1.7. If we are missing `@dev` there, then afaik that is a mistake and it can be fixed.

**Comment by mnocon** [comment]
@andrerom these are the values from ezplatform:1.7 (https://github.com/ezsystems/ezplatform/blob/1.7/composer.json#L30):
```
        "ezsystems/ezpublish-kernel": "~6.7.0@dev",
        "ezsystems/repository-forms": "~1.5.0@dev",
        "ezsystems/ezplatform-solr-search-engine": "^1.1@dev",
        "ezsystems/platform-ui-bundle": "~1.7.0@dev",
        "ezsystems/ez-support-tools": "~0.1.0@dev",
        "egulias/listeners-debug-command-bundle": "~1.9",
        "white-october/pagerfanta-bundle": "1.0.*",
        "hautelook/templated-uri-bundle": "~1.0 | ~2.0",
        "doctrine/doctrine-bundle": "~1.3",
        "symfony/expression-language": "~2.4",
        "sensio/framework-extra-bundle": "~3.0",
        "ezsystems/content-on-the-fly-prototype": "~0.1.7",
```
which made me think it's missing just here.

**Comment by mnocon** [comment]
@lserwatka this one can be merged

**Pull request merged**
