### PR TITLE
Move to use updates.ibexa.co

### PR DESCRIPTION
**Pull request by andrerom**
New updates server https://updates.ibexa.co is live, with all packages ready to start receiving testing on master.

Todo:
- [x] ~This should have failed on travis, as it should require change to composer auth for new domain on travis~ Due to no actual testing on this repo, QA will need to adapt CI.

TODO for QA:
- Composer auth token on all CI systems needs to be setup to ALSO* set todays network-key and tokens for https://updates.ibexa.co domain

_* As we will run with both for a while until all branches have migrated to new server_

### CODE REVIEW

**Comment by andrerom** [comment]
NOTE: This has *not* been tested on commerce, we have some work to do to setup product mapping correctly in https://github.com/ezsystems/support-site/blob/master/updates-app/config/package_access.yml with @mateuszbieniek for new and old product tiers

**Comment by andrerom** [comment]
Moving to #177 to start using updates.ibexa.co in dev branches before introducing it in stable branches later.

**Review by mnocon — APPROVED** [review]
```
TODO for QA:
Composer auth token on all CI systems needs to be setup to ALSO* set todays network-key and tokens for https://updates.ibexa.co domain
```
This is now done for all stable branches & repos, so +1 from me.

**Comment by andrerom** [comment]
This was merged as part of https://github.com/ezsystems/ezplatform-ee/commit/62e0d847a4bfb8e0754e2c28a3c810eb05d98a68

**Pull request closed without merging**
